version: 2

updates:
  # NPM dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "hadyfayed"
    assignees:
      - "hadyfayed"
    commit-message:
      prefix: "npm"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
    ignore:
      # Ignore major version updates for these packages
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "reactflow"
        update-types: ["version-update:semver-major"]

  # Composer dependencies
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
    open-pull-requests-limit: 5
    reviewers:
      - "hadyfayed"
    assignees:
      - "hadyfayed"
    commit-message:
      prefix: "composer"
      include: "scope"
    labels:
      - "dependencies"
      - "php"
      - "composer"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 5
    reviewers:
      - "hadyfayed"
    assignees:
      - "hadyfayed"
    commit-message:
      prefix: "github-actions"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"